name: Elice-CI CD

on:
  push:
    branches:[master]
  pull_request:
    branches:[master]
    
jobs:
  test-and-deploy:
    runs-on:ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version:"14"
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "sandy131712@gmail.com"
          buildpack:  "elice-elice-elice"
        
        
